### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jvyden** [Slendy/PubKeyFinder#1]
I noticed that this project lacks a license. Is this intentional?

**Comment by Slendy** [comment]
I didn't bother because the code shouldn't be used in any final product; it's just a tool. I went ahead and added one in 6d4f5337214f85b36bb2eee920ec546f69067669 if it benefits anyone though.

**Comment by jvyden** [comment]
By default, all rights are reserved until you say otherwise - including use of the software. I just wanted to feel safe with the rights clearly explained :sweat_smile: 

Thanks for adding a license!
